#!/bin/bash

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

ssh $(cat $RDMA_ROOT/apps/env/remote_host1) "$RDMA_ROOT/apps/zookeeper/install/bin/zkServer.sh start"
ssh $(cat $RDMA_ROOT/apps/env/remote_host2) "$RDMA_ROOT/apps/zookeeper/install/bin/zkServer.sh start"
