#!/bin/bash

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

MONGO_VER=3.2.4
YCSB_VER=0.7.0

cd $RDMA_ROOT/apps/mongodb

if [ ! -f mongodb-linux-x86_64-ubuntu1404-$MONGO_VER.tgz ]
then
    wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-$MONGO_VER.tgz
else
    echo "mongodb-linux-x86_64-ubuntu1404-$MONGO_VER.tgz exists."
fi

tar xzf mongodb-linux-x86_64-ubuntu1404-$MONGO_VER.tgz
rm mongodb-linux-x86_64-ubuntu1404-$MONGO_VER.tgz

mv mongodb-linux-x86_64-ubuntu1404-$MONGO_VER install

cd install

mkdir data
cd ..

scp -rp ./install  $(cat $RDMA_ROOT/apps/env/remote_host1):$RDMA_ROOT/apps/mongodb
scp -rp ./install  $(cat $RDMA_ROOT/apps/env/remote_host2):$RDMA_ROOT/apps/mongodb


if [ ! -f ycsb-mongodb-binding-$YCSB_VER.tar.gz ]
then
    wget https://github.com/brianfrankcooper/YCSB/releases/download/$YCSB_VER/ycsb-mongodb-binding-$YCSB_VER.tar.gz
else 
    echo "ycsb-mongodb-binding-$YCSB_VER.tar.gz exists"
fi

tar xzf ycsb-mongodb-binding-$YCSB_VER.tar.gz

mv ycsb-mongodb-binding-$YCSB_VER  ycsb-mongodb

cd ycsb-mongodb
sed -i "s/readproportion=1/readproportion=0/g" ./workloads/workloadc
sed -i "s/insertproportion=0/insertproportion=1/g" ./workloads/workloadc



