#!/bin/bash
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

ssh $(cat $RDMA_ROOT/apps/env/remote_host1) "killall -9 redis-server" 
ssh $(cat $RDMA_ROOT/apps/env/remote_host1) "killall -9 redis-server"

killall -9 redis-server
